[package]
name = "paper"
version = "0.1.0"
edition.workspace = true

[dependencies]
reqwest = { version = "0.12.20", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
